---
title: A Survey on Large Language Model based Autonomous Agents
author: Devin Ersoy
institute: Purdue University
date: 2024-01-17
format: revealjs
highlight-style: github
slide-number: c/t
---

## The Point
- Model *human thinking process*
- 192 autonomous agents exist
- Create a taxonomy of such efforts by answering the following:
	1. Which architecture should be designed to better use LLMs
	2. How to enable an *agent* to acquire capabilities for accomplishing specific tasks.

:::notes
- [Autonomous Agent Table](https://abyssinian-molybdenum-f76.notion.site/237e9f7515d543c0922c74f4c3012a77?v=0a309e53d6454afcbe7a5a7e169be0f9)
:::

## Three Main Taxonomies
- Agent Construction
- Agent Application
- Agent Evaluation

## Learning Types
- Learn from examples
	- Fine tune from certain data sets
- Learn from feedback
	- ex) VoyagerAI learned from Minecraft environment
- Learn from additional training

## Modules
- Profiling Module
- Learning Module
- Memory Module
- Planning Module
- Action Module

## Profiling Module
- The initial prompt telling AI what *role* its playing
	- Similar to what the GPT Builder does within its instructions

## Learning Module
- Learn from examples
	- Fine tune from certain data sets
- Learn from feedback
	- ex) VoyagerAI learned from Minecraft environment
- Learn from additional training

## Alignment Methods
### LLM Generation Method
- Automatic generation of profiles for an LLM

### Dataset Alignment Method
- Create agent profile based custom tailored to real world dataset

## Planning Module
- Initial/"Profile prompt" to create an initial plan/agenda
- Recursively prompt language model with summary description
- Decompose into hour long then to 5 minute chunks the given actions.
- Recursive process of breaking down and rethinking generated by the model

## Types of Planning
- Hand crafted?
- Generated by LLM?
- Database applied?

## Implementation Examples
- AutoGPT
- AgentGPT
- Smallville
- Voyager

## LLM Based Autonomous Agent Evaluation
- How well do the agents work?
- Generative agents
	- Subjective
	- Judged by humans graded based on how well they played games
	- How "believable?"
		- More believable than human beings with "full architecture"
	- Objective
		- Voyager: How quickly an axe is created

## Limitations
- Context Window
- Infinite Loop
	- ex) AgentGPT looping between tester agent and programmer agent
- 